import React, { useState, useEffect } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from 'recharts';
import { AlertTriangle, TrendingUp, Calendar, RefreshCw } from 'lucide-react';

function App() {
  const [historicalData, setHistoricalData] = useState([]);
  const [events, setEvents] = useState([]);
  const [changePoints, setChangePoints] = useState([]);
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetch data from Flask backend
    Promise.all([
      fetch('http://localhost:5001/api/v1/prices/historical').then(res => res.json()),
      fetch('http://localhost:5001/api/v1/events/correlations').then(res => res.json()),
      fetch('http://localhost:5001/api/v1/models/changepoints').then(res => res.json())
    ])
    .then(([pricesRes, eventsRes, cpRes]) => {
      // Crop dataset to recent years for optimal dashboard performance
      const filteredPrices = pricesRes.data.filter(item => item.Date >= '2019-01-01');
      setHistoricalData(filteredPrices);
      setEvents(eventsRes.data);
      setChangePoints(cpRes.data);
      setLoading(false);
    })
    .catch(err => {
      console.error("Error fetching dashboard backend APIs:", err);
      setLoading(false);
    });
  }, []);

  if (loading) {
    return (
      <div className="flex h-screen w-screen items-center justify-center bg-slate-900 text-white">
        <div className="flex flex-col items-center gap-4">
          <RefreshCw className="h-10 w-10 animate-spin text-teal-400" />
          <p className="text-lg">Injesting Pipeline Analytics...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 p-6 text-slate-100 font-sans">
      {/* Header */}
      <header className="mb-8 border-b border-slate-800 pb-6 flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white">Birhan Energies</h1>
          <p className="text-slate-400">Brent Crude Oil Sensitivity & Bayesian Change Point Analytics Dashboard</p>
        </div>
        <div className="flex items-center gap-2 bg-slate-900 px-4 py-2 rounded-lg border border-slate-800">
          <span className="h-2.5 w-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
          <span className="text-xs font-semibold text-slate-300">API Pipeline Active</span>
        </div>
      </header>

      {/* Metric Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="bg-slate-900 p-6 rounded-xl border border-slate-850 shadow-lg">
          <div className="flex justify-between items-center mb-2">
            <h3 className="text-sm font-medium text-slate-400">Isolated Structural Eras</h3>
            <TrendingUp className="h-5 w-5 text-teal-400" />
          </div>
          <p className="text-2xl font-semibold text-white">{changePoints.length} Major Change Points</p>
          <span className="text-xs text-slate-500">Isolate parameters generated by PyMC model</span>
        </div>

        <div className="bg-slate-900 p-6 rounded-xl border border-slate-850 shadow-lg">
          <div className="flex justify-between items-center mb-2">
            <h3 className="text-sm font-medium text-slate-400">Monitored Geopolitical Shocks</h3>
            <AlertTriangle className="h-5 w-5 text-amber-500" />
          </div>
          <p className="text-2xl font-semibold text-white">{events.length} Key Global Events</p>
          <span className="text-xs text-slate-500">Cross-referenced historical timelines</span>
        </div>

        <div className="bg-slate-900 p-6 rounded-xl border border-slate-850 shadow-lg">
          <div className="flex justify-between items-center mb-2">
            <h3 className="text-sm font-medium text-slate-400">Active Pipeline Records</h3>
            <Calendar className="h-5 w-5 text-indigo-400" />
          </div>
          <p className="text-2xl font-semibold text-white">{historicalData.length} Days</p>
          <span className="text-xs text-slate-500">Tracking daily price metrics (2019-Present)</span>
        </div>
      </div>

      {/* Main Charts & Controls Panel */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        {/* Interactive Chart (Left 3 Columns) */}
        <div className="lg:col-span-3 bg-slate-900 p-6 rounded-xl border border-slate-850 shadow-xl">
          <h2 className="text-lg font-semibold text-white mb-4">Historical Brent Spot Price Correlation</h2>
          <div className="h-[400px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={historicalData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                <XAxis dataKey="Date" stroke="#94a3b8" />
                <YAxis domain={['auto', 'auto']} stroke="#94a3b8" />
                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', color: '#f8fafc' }} />
                <Line type="monotone" dataKey="Price" stroke="#06b6d4" strokeWidth={2} dot={false} />
                {/* Highlight Selected Event */}
                {selectedEvent && (
                  <ReferenceLine x={selectedEvent.Date} stroke="#f59e0b" strokeWidth={2} strokeDasharray="5 5" label={{ value: selectedEvent.Event, fill: '#f59e0b', position: 'top' }} />
                )}
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Action Panel (Right 1 Column) */}
        <div className="space-y-6">
          {/* Interactive Event Highlighters */}
          <div className="bg-slate-900 p-6 rounded-xl border border-slate-850 shadow-xl h-[260px] overflow-y-auto">
            <h2 className="text-sm font-semibold text-slate-300 uppercase tracking-wider mb-4">Geopolitical Events</h2>
            <div className="space-y-2">
              {events.slice(-5).map((evt, idx) => (
                <button
                  key={idx}
                  onClick={() => setSelectedEvent(evt)}
                  className={`w-full text-left p-3 rounded-lg text-xs transition duration-200 border ${
                    selectedEvent?.Date === evt.Date 
                      ? 'bg-amber-950/40 border-amber-500 text-amber-200' 
                      : 'bg-slate-950 border-slate-850 hover:border-slate-700 text-slate-300'
                  }`}
                >
                  <div className="font-bold mb-1">{evt.Event}</div>
                  <div className="text-slate-400">{evt.Date}</div>
                </button>
              ))}
            </div>
          </div>

          {/* PyMC Model Changes View */}
          <div className="bg-slate-900 p-6 rounded-xl border border-slate-850 shadow-xl">
            <h2 className="text-sm font-semibold text-slate-300 uppercase tracking-wider mb-3">Model-Isolated Shocks</h2>
            <div className="space-y-3">
              {changePoints.map((cp) => (
                <div key={cp.id} className="p-3 bg-slate-950 rounded-lg border border-slate-850 text-xs">
                  <div className="flex justify-between items-center mb-1">
                    <span className="font-bold text-teal-400">{cp.detected_date}</span>
                    <span className="text-[10px] text-slate-500">{cp.confidence_level}</span>
                  </div>
                  <p className="text-slate-300 mb-2">{cp.associated_event}</p>
                  <div className="grid grid-cols-2 gap-2 text-[10px] text-slate-400 border-t border-slate-850 pt-2">
                    <div>Before: <span className="font-semibold text-white">${cp.avg_price_before}</span></div>
                    <div>After: <span className="font-semibold text-white">${cp.avg_price_after}</span></div>
                    <div className="col-span-2">Shift: <span className={`font-bold ${cp.percentage_change < 0 ? 'text-rose-400' : 'text-emerald-400'}`}>{cp.percentage_change}%</span></div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;